language: php
dist: xenial
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - CONSUL_HTTP_ADDR="127.0.0.1:8500"

before_install: phpenv config-add ./tests/php.ini

install:
  - mkdir -p $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  - wget "https://releases.hashicorp.com/consul/1.6.2/consul_1.6.2_linux_amd64.zip"
  - unzip consul_1.6.2_linux_amd64.zip -d $HOME/bin
  - chmod +x $HOME/bin/consul
  - composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

script:
  - ./vendor/bin/phpunit -c phpunit.xml
